services:
  database:
    image: registry.gitlab.com/cencosud-ds/cencommerce/utils/docker-images/postgres:14.6-alpine3.17
    # image: mysql:8.0.23
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
      # MYSQL_RANDOM_ROOT_PASSWORD: true
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: ${DB_NAME}
    container_name: ${APP_NAME}-db
    networks:
      - network
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - mysqldata:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile_local
      target: development
      args:
        APP_PORT: ${APP_PORT}
        HC_LIB_FLAGS_TOKEN: ${HC_LIB_FLAGS_TOKEN}
    env_file:
      - .env
    image: ${APP_NAME}-api:latest
    environment:
      NODE_ENV: development
      DB_HOST: ${APP_NAME}-db
    container_name: ${APP_NAME}-api
    networks:
      - network
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    command: npm run start:debug
networks:
  network:
    name: ${APP_NAME}-network
volumes:
  pgdata:
  # mysqldata:
    name: ${APP_NAME}-db-data
